name: Rust CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
      - 'BTH-*/*'

jobs:
  build:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Rust using rustup
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt

    # Cache dependencies
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # Build the project
    - name: Build
      run: cargo build --workspace --all-targets

    # Run tests
    - name: Run tests
      run: cargo test --workspace --all-targets

    # Run clippy for linting
    - name: Run Clippy
      run: cargo clippy --workspace --all-targets -- -D warnings

    # Run rustfmt for formatting check
    - name: Check Formatting
      run: cargo fmt -- --check
